In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2017_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,1790,"PULICATE LAKE , NELLORE \nDIST.",LAKE,ANDHRA \nPRADESH,27.0,28.0,5.1,6.9,7.1,8.5,3270.0,156600.0,1.0,2.3,0.65,6.90,2.0,2.0,800.0,1600.0
1,2353,"KONDACHARLA-AAVA LAKE, \nPARAWADA PHARMA CITY,...",LAKE,ANDHRA \nPRADESH,24.0,28.0,5.9,6.8,6.9,8.4,597.0,1034.0,1.3,2.3,1.16,3.36,11.0,29.0,350.0,2400.0
2,2205,"MER BEEL AT MADHABPUR, \nASSAM",LAKE,ASSAM,20.0,27.0,2.2,7.2,5.7,7.0,50.0,128.0,1.0,16.2,0.10,1.70,300.0,2000.0,360.0,6400.0
3,2206,"DALONI BEEL NEAR \nJOGIGHOPA, ASSAM",LAKE,ASSAM,22.0,36.0,5.1,6.0,6.6,7.8,54.0,153.0,0.9,2.8,0.10,1.40,300.0,1200.0,300.0,5300.0
4,1263,ELANGABEEL SYSTEM POND \n(CONNECTED TO R. KOLA...,POND,ASSAM,22.0,34.0,0.7,4.6,6.8,8.4,263.0,972.0,4.5,14.7,0.80,5.70,1100.0,3500.0,730.0,21000.0

In [2]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [3]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,27.0,5.1,7.1,3270.0,1.0,0.65,2.0,800.0
1,LAKE,ANDHRA \nPRADESH,24.0,5.9,6.9,597.0,1.3,1.16,11.0,350.0
2,LAKE,ASSAM,20.0,2.2,5.7,50.0,1.0,0.10,300.0,360.0
3,LAKE,ASSAM,22.0,5.1,6.6,54.0,0.9,0.10,300.0,300.0
4,POND,ASSAM,22.0,0.7,6.8,263.0,4.5,0.80,1100.0,730.0

In [5]:
df.isnull().sum()

Type Water Body               0
State Name                    0
Min Temperature               4
Min Dissolved Oxygen          1
Min pH                        1
Min Conductivity              4
Min BOD                       6
Min Nitrate N + Nitrite N    21
Min Fecal Coliform           54
Min Total Coliform           34
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min pH', 'Min Conductivity', 'Min BOD', 'Min Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Min Total Coliform'],
      dtype='object')
Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen'],
      dtype='object')

In [7]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature               object
Min Dissolved Oxygen          object
Min pH                       float64
Min Conductivity             float64
Min BOD                      float64
Min Nitrate N + Nitrite N    float64
Min Fecal Coliform           float64
Min Total Coliform           float64
dtype: object

In [9]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [10]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [11]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [12]:
df.dropna(inplace=True)

In [13]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [14]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [15]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [16]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [19]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
31,LAKE,BIHAR,19.0,5.4,7.2,222.0,2.1,0.0,7000.0,15000.0
33,POND,BIHAR,18.0,6.2,7.1,340.0,2.6,0.0,1700.0,3900.0
44,LAKE,GOA,26.0,0.0,6.4,289.0,1.1,0.0,35000.0,54000.0
101,LAKE,KARNATAKA,21.0,2.8,6.4,1203.0,6.5,0.1,1100.0,4700.0
102,LAKE,KARNATAKA,24.0,5.2,7.4,526.0,4.0,0.2,920.0,4600.0
...,...,...,...,...,...,...,...,...,...,...
360,POND,UTTAR PRADESH,16.0,0.0,7.1,877.0,85.0,0.0,1200.0,28000.0
364,LAKE,WEST BENGAL,21.0,4.1,7.6,618.0,5.3,0.0,70000.0,90000.0
365,LAKE,WEST BENGAL,21.0,3.9,7.5,629.0,4.0,0.0,80000.0,110000.0
366,LAKE,WEST BENGAL,21.0,5.3,7.8,615.0,1.9,0.0,80000.0,110000.0
368,LAKE,WEST BENGAL,10.0,6.4,6.7,64.0,2.3,0.3,2700.0,9000.0

In [20]:
outliers.index

Index([ 31,  33,  44, 101, 102, 103, 104, 105, 106, 108, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 124, 125, 126, 127, 129, 130,
       131, 137, 138, 140, 142, 143, 144, 146, 147, 148, 150, 151, 152, 154,
       155, 156, 157, 158, 159, 162, 163, 164, 165, 188, 191, 357, 358, 359,
       360, 364, 365, 366, 368],
      dtype='int64')

In [21]:
df.drop(outliers.index,axis=0,inplace=True)

In [23]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)