In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2018_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,1790,"PULICATE LAKE , NELLORE \nDIST., A.P",LAKE,ANDHRA \nPRADESH,28.0,28.0,5.2,7.4,7.1,8.0,8670.0,47200.0,1.6,7.1,1.3,2.9,2.0,4.0,1100,1600.0
1,2353,"KONDACHARLAAAVA LAKE, \nPARAWADA PHARMA CITY, ...",LAKE,ANDHRA \nPRADESH,26.0,30.0,5.5,7.0,7.1,8.3,817.0,1108.0,1.2,1.5,1.2,2.8,15.0,39.0,350,2400.0
2,2205,"MER BEEL AT MADHABPUR, \nASSAM",LAKE,ASSAM,15.0,24.0,0.5,8.9,5.6,7.2,30.0,116.0,3.2,62.0,0.2,8.0,2.0,2700.0,2,21000.0
3,2206,"DALONI BEEL NEAR \nJOGIGHOPA, ASSAM",LAKE,ASSAM,20.0,36.0,5.1,7.9,6.8,9.5,52.0,197.0,0.8,2.1,0.1,1.1,2.0,360.0,2,910.0
4,1263,ELANGABEEL SYSTEM POND \n(CONNECTED TO R. KOLANG),POND,ASSAM,20.0,36.0,1.6,6.0,6.7,7.8,461.0,958.0,3.8,18.0,0.7,2.3,300.0,2800.0,360,110000.0

In [2]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [3]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,28.0,5.2,7.1,8670.0,1.6,1.3,2.0,1100
1,LAKE,ANDHRA \nPRADESH,26.0,5.5,7.1,817.0,1.2,1.2,15.0,350
2,LAKE,ASSAM,15.0,0.5,5.6,30.0,3.2,0.2,2.0,2
3,LAKE,ASSAM,20.0,5.1,6.8,52.0,0.8,0.1,2.0,2
4,POND,ASSAM,20.0,1.6,6.7,461.0,3.8,0.7,300.0,360

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [5]:
df.isnull().sum()

Type Water Body               0
State Name                    0
Min Temperature               5
Min Dissolved Oxygen          3
Min pH                        1
Min Conductivity              6
Min BOD                       3
Min Nitrate N + Nitrite N    33
Min Fecal Coliform           59
Min Total Coliform           41
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min Temperature', 'Min Conductivity', 'Min Fecal Coliform'], dtype='object')
Index(['Type Water Body', 'State Name', 'Min Dissolved Oxygen', 'Min pH',
       'Min BOD', 'Min Nitrate N + Nitrite N', 'Min Total Coliform'],
      dtype='object')

In [7]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature              float64
Min Dissolved Oxygen          object
Min pH                        object
Min Conductivity             float64
Min BOD                       object
Min Nitrate N + Nitrite N     object
Min Fecal Coliform           float64
Min Total Coliform            object
dtype: object

In [8]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [9]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [13]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [14]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [16]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
30,POND,ASSAM,20.0,2.5,6.2,20.0,1.3,0.1,600.0,910
32,LAKE,BIHAR,17.0,8.2,7.2,149.0,2.4,0.0,4000.0,11000
33,LAKE,BIHAR,14.0,7.9,6.9,328.0,2.1,0.0,4000.0,11000
34,LAKE,BIHAR,23.0,5.7,6.7,347.0,1.8,0.1,3100.0,7000
35,POND,BIHAR,18.0,5.6,7.2,437.0,2.5,0.0,2100.0,4600
...,...,...,...,...,...,...,...,...,...,...
422,LAKE,WEST BENGAL,20.0,6.5,7.7,641.0,1.5,0.0,13000.0,23000
423,LAKE,WEST BENGAL,10.0,6.2,6.8,5.0,1.4,0.0,2600.0,9000
424,LAKE,WEST BENGAL,4.0,6.2,6.9,88.0,2.4,0.2,2200.0,5000
427,LAKE,WEST BENGAL,19.0,5.4,7.0,178.0,1.5,BDL,1100.0,1400
428,LAKE,WEST BENGAL,17.5,4.1,7.0,438.0,2.5,BDL,3000.0,5000

In [17]:
outliers.index

Index([ 30,  32,  33,  34,  35,  36,  42,  50,  73,  74, 115, 116, 117, 118,
       119, 120, 124, 125, 126, 130, 132, 133, 134, 136, 137, 138, 139, 140,
       142, 153, 156, 160, 165, 167, 169, 171, 175, 176, 177, 180, 182, 187,
       188, 202, 204, 205, 206, 217, 220, 221, 222, 288, 289, 291, 292, 293,
       413, 414, 415, 416, 419, 420, 421, 422, 423, 424, 427, 428],
      dtype='int64')

In [18]:
df.drop(outliers.index,axis=0,inplace=True)

In [19]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)