In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2019_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,1790,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA \nPRADESH,18.0,28.0,4.9,5.5,6.7,8.2,21840.0,47890.0,2.20,2.80,0.46,2.80,3,4.0,210,1600
1,2353,"KONDAKARLA-AAVA LAKE, PARAWADA \nPHARMA CITY, ...",LAKE,ANDHRA \nPRADESH,24.0,30.0,5.0,6.8,7.0,8.5,714.0,1950.0,1.60,4.20,0.00,5.82,11,23.0,150,1100
2,4368,"KOLLERU LAKE KOKKIRAYALANKA (V), \nKAILALUR (M)",LAKE,ANDHRA \nPRADESH,25.0,28.0,3.7,7.5,7.2,8.1,979.0,14730.0,1.70,5.40,0.00,3.47,4,20.0,150,1300
3,4391,"CHENGAMBAKAM TANK IN SRI CITY SEZ, \nTIRUPATHI",TANK,ANDHRA \nPRADESH,25.0,36.0,3.2,6.1,6.8,7.9,228.0,1098.0,2.00,22.00,0.00,4.40,100,200.0,400,1400
4,1529,"DEEPAR BEEL, ASSAM",LAKE,ASSAM,22.0,34.0,4.6,11.0,7.1,8.0,144.0,273.0,2.70,4.80,1.10,2.00,2,360.0,360,1500

In [2]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [3]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,18.0,4.9,6.7,21840.0,2.20,0.46,3,210
1,LAKE,ANDHRA \nPRADESH,24.0,5.0,7.0,714.0,1.60,0.00,11,150
2,LAKE,ANDHRA \nPRADESH,25.0,3.7,7.2,979.0,1.70,0.00,4,150
3,TANK,ANDHRA \nPRADESH,25.0,3.2,6.8,228.0,2.00,0.00,100,400
4,LAKE,ASSAM,22.0,4.6,7.1,144.0,2.70,1.10,2,360

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [5]:
df.isnull().sum()

Type Water Body               0
State Name                    0
Min Temperature               3
Min Dissolved Oxygen          4
Min pH                        2
Min Conductivity              6
Min BOD                       3
Min Nitrate N + Nitrite N    36
Min Fecal Coliform           51
Min Total Coliform           51
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min Temperature', 'Min pH', 'Min Conductivity'], dtype='object')
Index(['Type Water Body', 'State Name', 'Min Dissolved Oxygen', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [7]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature              float64
Min Dissolved Oxygen          object
Min pH                       float64
Min Conductivity             float64
Min BOD                       object
Min Nitrate N + Nitrite N     object
Min Fecal Coliform            object
Min Total Coliform            object
dtype: object

In [8]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [9]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [13]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [14]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [16]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,18.0,4.9,6.7,21840.0,2.20,0.46,3,210
47,LAKE,DELHI,8.0,2.8,8.1,6500.0,27.00,0.31,17000,22000
59,LAKE,GUJARAT,25.0,6.0,8.1,2408.0,11.00,0.06,12,120
74,LAKE,GUJARAT,26.0,2.8,8.4,6419.0,14.00,0.00,12,70
75,LAKE,GUJARAT,26.0,3.3,8.3,2892.0,9.00,0.00,2,2
153,LAKE,KARNATAKA,22.0,BDL,7.1,2200.0,13.00,1.10,940,5400
256,TANK,KARNATAKA,26.0,5.4,9.1,3170.0,9.00,0.10,2,BDL
268,LAKE,KERALA,19.0,3.4,7.5,18120.0,1.40,0.98,260,480
269,LAKE,KERALA,19.0,5.4,7.4,12260.0,1.40,0.79,100,220
273,LAKE,KERALA,26.0,1.1,7.5,6458.0,0.50,0.03,2,20
353,LAKE,ODISHA,20.0,6.4,6.6,1606.0,0.80,0.20,20,78
355,LAKE,ODISHA,13.0,6.2,7.4,9842.0,1.20,0.13,2,BDL
389,LAKE,RAJASTHAN,15.0,0.5,7.9,2500.0,5.00,2.21,39,120
399,LAKE,TAMIL NADU,24.0,3.1,6.1,24200.0,2.00,0.00,2,BDL
406,LAKE,TELANGANA,26.0,0.0,7.2,2132.0,36.00,4.58,20,350
417,LAKE,TELANGANA,23.0,0.0,6.9,1720.0,32.00,1.00,20,330
419,LAKE,TELANGANA,28.0,0.1,7.0,1783.0,24.00,12.00,2,BDL
440,LAKE,TELANGANA,27.0,1.2,7.0,2200.0,50.00,51.87,2,300
445,LAKE,TELANGANA,27.0,0.1,7.1,1660.0,24.00,16.00,2,BDL
447,LAKE,TELANGANA,22.0,0.0,7.2,1510.0,22.00,0.98,22,350
450,POND,TELANGANA,26.0,0.0,7.0,6570.0,122.00,8.00,22,350
452,POND,TELANGANA,21.0,0.0,6.5,3064.0,77.00,7.75,2,BDL
456,POND,TELANGANA,26.0,0.0,7.0,1520.0,24.00,3.72,19,290
463,TANK,TELANGANA,18.0,1.3,6.8,1840.0,2.00,12.37,2,BDL
464,TANK,TELANGANA,21.0,5.5,6.4,2441.0,3.40,9.28,2,BDL
465,TANK,TELANGANA,23.0,0.0,6.9,3072.0,26.00,10.00,14,350
466,TANK,TELANGANA,21.0,5.1,6.7,2021.0,2.40,15.30,2,BDL
467,TANK,TELANGANA,26.0,0.0,7.1,1524.0,24.00,2.60,20,350
474,TANK,TELANGANA,28.0,0.0,7.2,1669.0,28.00,15.10,46,350
478,TANK,TELANGANA,21.0,4.5,6.5,4860.0,6.30,20.62,2,BDL
484,TANK,TELANGANA,23.0,4.6,6.5,3370.0,5.60,21.40,2,BDL
486,TANK,TELANGANA,23.0,4.9,7.3,1598.0,3.40,10.37,2,BDL

In [17]:
outliers.index

Index([  0,  47,  59,  74,  75, 153, 256, 268, 269, 273, 353, 355, 389, 399,
       406, 417, 419, 440, 445, 447, 450, 452, 456, 463, 464, 465, 466, 467,
       474, 478, 484, 486],
      dtype='int64')

In [18]:
df.drop(outliers.index,axis=0,inplace=True)

In [19]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)