In [26]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2020_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,1790,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA \nPRADESH,21,26,3.8,4.8,7.0,8.4,18830,57090,2.2,2.8,0.74,1.45,3,3,75,210
1,2353,"KONDAKARLA-AAVA LAKE, \nPARAWADA PHARMA CITY, ...",LAKE,ANDHRA \nPRADESH,25,28,3.6,6.8,7.1,8.3,580,890,2.4,4.8,1.03,4.52,15,23,150,460
2,4368,"KOLLERU LAKE \nKOKKIRAYALANKA (V), \nKAILALUR (M)",LAKE,ANDHRA \nPRADESH,23,29,0.5,5.4,6.8,8.4,675,13800,1.7,6.2,1.3,8.62,11,23,150,1100
3,4391,"CHENGAMBAKAM TANK IN SRI \nCITY SEZ, TIRUPATHI",TANK,ANDHRA \nPRADESH,26,30,5.3,6.7,6.4,7.6,206,670,0.8,2.5,0.11,3.3,47,200,210,600
4,1529,"DEEPAR BEEL, ASSAM",LAKE,ASSAM,18,35,7.2,10.2,7.3,8.0,188,240,2.1,3.8,1,1.8,300,910,720,1500

In [27]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [28]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,21,3.8,7.0,18830,2.2,0.74,3,75
1,LAKE,ANDHRA \nPRADESH,25,3.6,7.1,580,2.4,1.03,15,150
2,LAKE,ANDHRA \nPRADESH,23,0.5,6.8,675,1.7,1.3,11,150
3,TANK,ANDHRA \nPRADESH,26,5.3,6.4,206,0.8,0.11,47,210
4,LAKE,ASSAM,18,7.2,7.3,188,2.1,1,300,720

In [29]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [30]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [31]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min pH'], dtype='object')
Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [32]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature               object
Min Dissolved Oxygen          object
Min pH                       float64
Min Conductivity              object
Min BOD                       object
Min Nitrate N + Nitrite N     object
Min Fecal Coliform            object
Min Total Coliform            object
dtype: object

In [33]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [34]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [35]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [36]:
df.dropna(inplace=True)

In [37]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [38]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [39]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [40]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [41]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
61,LAKE,GOA,27,5.6,5.6,42,0.1,0.11,1100,2200
62,LAKE,GOA,27,3.9,5.8,41,0.1,0.11,8,13
84,LAKE,GUJARAT,27,0.6,8.4,704,6,0.15,21,220
85,LAKE,GUJARAT,27,4.6,9.0,2451,6,0.04,26,120
164,LAKE,KARNATAKA,25,3.8,5.3,575,3,0.84,460,5400
172,LAKE,KARNATAKA,25,0.5,5.5,340,6,0.86,84,920
176,LAKE,KARNATAKA,24,0.2,5.7,243,4,0.87,3300,24000
214,TANK,KARNATAKA,24,3.8,8.6,810,16,0.1,6300,22000
222,TANK,KARNATAKA,22,4,5.6,187,3,0.41,700,5400
275,TANK,KARNATAKA,21,4.9,8.4,760,1.5,0.81,900,1600
320,POND,LAKSHADWEEP,31,-,8.7,471,-,-,-,-
385,TANK,MIZORAM,13,4.5,4.9,33,1.3,0.01,-,-
412,LAKE,RAJASTHAN,24,7,8.3,540,0.7,1.15,64,120
416,LAKE,RAJASTHAN,17,4.1,8.3,310,1,0.92,39,75
417,LAKE,RAJASTHAN,17,4,8.4,420,0.8,1.1,39,64
419,LAKE,RAJASTHAN,22,7.2,8.4,470,1,1.24,23,39
420,LAKE,RAJASTHAN,22,7,8.3,480,1.5,1.24,23,64
474,LAKE,TELANGANA,27,5.2,8.5,561,6,16,5,33

In [42]:
outliers.index

Index([ 61,  62,  84,  85, 164, 172, 176, 214, 222, 275, 320, 385, 412, 416,
       417, 419, 420, 474],
      dtype='int64')

In [43]:
df.drop(outliers.index,axis=0,inplace=True)

In [44]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)