In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2021_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,4368.0,"KOLLERU LAKE KOKKIRAYALANKA (V),\nKAILALUR (M)",LAKE,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,"KONDAKARLA-AAVA LAKE, PARAWADA \nPHARMA CITY, ...",LAKE,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,"CHENGAMBAKAM TANK IN SRI CITY SEZ, \nTIRUPATHI",TANK,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,ANNAMAYYA PROJECT ON CHEYYERU \nRESERVOIR,Wetland,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727

In [2]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [3]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA PRADESH,24.0,3.2,7.0,245,1.6,1.02,9,120
1,LAKE,ANDHRA PRADESH,26.0,3.0,6.9,599,1.9,0.77,15,150
2,LAKE,ANDHRA PRADESH,18.0,4.2,7.2,28000,2.4,1.20,3,47
3,TANK,ANDHRA PRADESH,22.0,5.4,6.3,180,1.0,0.34,24,170
4,Wetland,ANDHRA PRADESH,21.0,5.4,7.3,496,1.0,0.35,43,240

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [5]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              3
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             2
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           1
Min Total Coliform           1
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min Temperature', 'Min pH'], dtype='object')
Index(['Type Water Body', 'State Name', 'Min Dissolved Oxygen',
       'Min Conductivity', 'Min BOD', 'Min Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Min Total Coliform'],
      dtype='object')

In [7]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature              float64
Min Dissolved Oxygen          object
Min pH                       float64
Min Conductivity              object
Min BOD                       object
Min Nitrate N + Nitrite N     object
Min Fecal Coliform            object
Min Total Coliform            object
dtype: object

In [8]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [9]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [13]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [14]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

In [16]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
79,LAKE,DELHI,34.0,0.3,8.7,940,64.0,2.38,49,79
81,LAKE,GOA,27.0,4.8,5.7,40,1.0,0.32,2,2
97,LAKE,GUJARAT,25.0,4.8,8.5,2571,7.0,0.32,33,280
101,LAKE,GUJARAT,24.0,4.2,8.3,2669,3.0,0.30,12,63
102,LAKE,GUJARAT,26.0,0.3,8.3,1838,10.0,0.16,94,280
260,TANK,KARNATAKA,25.0,4.8,5.4,123,2.0,0.30,4600,35000
267,TANK,KARNATAKA,21.0,4.0,8.4,1180,1.1,0.40,920,1600
335,LAKE,KERALA,26.0,5.2,5.7,105,1.7,0.30,200,700
407,LAKE,NAGALAND,19.0,1.4,2.0,72,1.3,0.60,-,-
433,LAKE,RAJASTHAN,23.0,7.1,8.3,530,1.2,1.66,23,75
434,LAKE,RAJASTHAN,24.0,7.2,8.4,520,1.3,1.42,39,64
435,LAKE,RAJASTHAN,18.0,0.5,8.5,1210,3.2,2.50,93,210
444,LAKE,RAJASTHAN,17.0,4.6,8.3,450,1.2,1.43,75,120

In [17]:
outliers.index

Index([79, 81, 97, 101, 102, 260, 267, 335, 407, 433, 434, 435, 444], dtype='int64')

In [18]:
df.drop(outliers.index,axis=0,inplace=True)

In [19]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)