In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\archive (5)\2022_lake_data.csv")
df.head()

,STN Code,Name of Monitoring Location,Type Water Body,State Name,Min Temperature,Max Temperature,Min Dissolved Oxygen,Max Dissolved Oxygen,Min pH,Max pH,Min Conductivity,Max Conductivity,Min BOD,Max BOD,Min Nitrate N + Nitrite N,Max Nitrate N + Nitrite N,Min Fecal Coliform,Max Fecal Coliform,Min Total Coliform,Max Total Coliform
0,5159.0,"GARGEYAPURAM LAKE \nGARGEYAPURAM (V), \nKURNOO...",LAKE,ANDHRA \nPRADESH,22,27,3.9,6.5,7.1,7.9,374,1370,1.5,3.7,0.33,5.90,214,525,816,1733
1,4368.0,"KOLLERU LAKE, \nKOKKIRAYALANKA (V), \nKAILALUR...",LAKE,ANDHRA \nPRADESH,18,29,3.2,8.7,7.2,8.6,215,1800,1.6,6.1,0.69,2.79,7,21,210,460
2,2353.0,"KONDAKARLA-AAVA \nLAKE, KONDAKARLA, \nVISHAKHA...",LAKE,ANDHRA \nPRADESH,26,29,3.4,6.4,7.1,8.5,402,888,2.4,4.8,1.12,2.42,7,39,150,240
3,5147.0,"PALASAMUDRAM LAKE, \nPALASAMUDRAM (V), \nPENUK...",LAKE,ANDHRA \nPRADESH,23,27,5.1,6.1,6.6,7.8,322,535,1.5,2.2,0.32,1.26,89,388,491,1046
4,1790.0,"PULICATE LAKE, SRIHARI \nKOTA, SULLURUPETA (M)",LAKE,ANDHRA \nPRADESH,18,22,5.7,6.8,7.4,8.1,31100,42200,2.6,2.9,1.11,1.78,3,62,75,689

In [2]:
df.columns

Index(['STN Code', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Min Temperature', 'Max Temperature',
       'Min Dissolved Oxygen', 'Max Dissolved Oxygen', 'Min pH', 'Max pH',
       'Min Conductivity', 'Max Conductivity', 'Min BOD', 'Max BOD',
       'Min Nitrate N + Nitrite N', 'Max Nitrate N + Nitrite N',
       'Min Fecal Coliform', 'Max Fecal Coliform', 'Min Total Coliform',
       'Max Total Coliform'],
      dtype='object')

In [3]:
# Drop unnecessary columns
df.drop([
    'STN Code',
    'Name of Monitoring Location',
    'Max Temperature',
    'Max Dissolved Oxygen',
    'Max pH',
    'Max Conductivity',
    'Max BOD',
    'Max Nitrate N + Nitrite N',
    'Max Fecal Coliform',
    'Max Total Coliform'
], axis=1, inplace=True)

# View cleaned data
df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
0,LAKE,ANDHRA \nPRADESH,22,3.9,7.1,374,1.5,0.33,214,816
1,LAKE,ANDHRA \nPRADESH,18,3.2,7.2,215,1.6,0.69,7,210
2,LAKE,ANDHRA \nPRADESH,26,3.4,7.1,402,2.4,1.12,7,150
3,LAKE,ANDHRA \nPRADESH,23,5.1,6.6,322,1.5,0.32,89,491
4,LAKE,ANDHRA \nPRADESH,18,5.7,7.4,31100,2.6,1.11,3,75

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [5]:
df.isnull().sum()

Type Water Body               9
State Name                    9
Min Temperature              15
Min Dissolved Oxygen          9
Min pH                        9
Min Conductivity             13
Min BOD                      10
Min Nitrate N + Nitrite N    13
Min Fecal Coliform            9
Min Total Coliform           10
dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print(numeric_cols)
print(categorical_cols)

Index(['Min pH'], dtype='object')
Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min Conductivity', 'Min BOD',
       'Min Nitrate N + Nitrite N', 'Min Fecal Coliform',
       'Min Total Coliform'],
      dtype='object')

In [7]:
df.dtypes

Type Water Body               object
State Name                    object
Min Temperature               object
Min Dissolved Oxygen          object
Min pH                       float64
Min Conductivity              object
Min BOD                       object
Min Nitrate N + Nitrite N     object
Min Fecal Coliform            object
Min Total Coliform            object
dtype: object

In [8]:
for col in numeric_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

In [9]:
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy="mean")
df[numeric_cols] = mean_imputer.fit_transform(df[numeric_cols])

In [13]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [14]:
df.isnull().sum()

Type Water Body              0
State Name                   0
Min Temperature              0
Min Dissolved Oxygen         0
Min pH                       0
Min Conductivity             0
Min BOD                      0
Min Nitrate N + Nitrite N    0
Min Fecal Coliform           0
Min Total Coliform           0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

8

In [17]:
df = df.drop_duplicates()

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1- 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
outliers

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min Nitrate N + Nitrite N,Min Fecal Coliform,Min Total Coliform
87,LAKE,GOA,27,3.0,5.5,42,1.0,0.32,240,350
89,LAKE,GOA,28,4.0,5.8,72,1.0,0.32,490,790
93,LAKE,GOA,27,6.0,5.3,29,1.0,0.32,1300,1700
100,LAKE,GUJARAT,25,4.5,8.4,1108,1.6,0.42,18,110
103,LAKE,GUJARAT,22,2.9,8.3,2644,2.2,0.32,540,920
106,LAKE,GUJARAT,23,0.3,8.7,3408,3.7,0.32,49,170
128,LAKE,JAMMU & \nKASHMIR,21,7.2,8.5,196,1.0,-,-,-
166,LAKE,KARNATAKA,25,0.3,2.2,898,6.0,2.50,410,3500
171,LAKE,KARNATAKA,17,4.6,8.3,1006,3.0,0.76,1100,5800
241,POND,KARNATAKA,22,3.3,8.3,1020,1.0,2.69,430,1600
282,TANK,KARNATAKA,25,0.3,5.7,184,4.0,0.69,630,16000
335,POND,KERALA,27,6.2,5.5,82,1.0,0.30,40,100
336,POND,LAKSHADWE\nEP,31,-,8.5,290,-,-,540,540
415,LAKE,PUDUCHERR\nY,28,6.0,8.5,310,1.0,0.32,2,84
425,LAKE,RAJASTHAN,20,2.6,2.0,2430,3.3,2.49,150,210
447,LAKE,TAMIL NADU,14,2.1,5.4,248,1.0,0.32,170,320
460,LAKE,TELANGANA,25,0.3,5.8,1199,2.0,2.62,11,350
552,POND,TELANGANA,18,0.3,5.4,2406,36.0,12.24,9,142
560,POND,TELANGANA,25,2.6,8.3,460,2.3,1.06,2,39

In [20]:
outliers.index

Index([ 87,  89,  93, 100, 103, 106, 128, 166, 171, 241, 282, 335, 336, 415,
       425, 447, 460, 552, 560],
      dtype='int64')

In [21]:
df.drop(outliers.index,axis=0,inplace=True)

In [22]:
df.to_csv(r"C:\AIML waterbourne project\Lake dataset.csv", index=False)