In [6]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\Mohammed Abuzar\OneDrive\Pictures\Documents\AIML datasets\Indian Rainfall Dataset District-wise Daily Measurements.csv")
df.head()

,state,district,month,1st,2nd,3rd,4th,5th,6th,7th,...,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st
0,Andaman & Nicobar,Nicobars,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,Andaman & Nicobar,North And Middle Andaman,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,Andaman & Nicobar,South Andamans,1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,Andhra Pradesh,Anantapur,1,0.379965,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.205834,0.671002,0.028994,0.0,0.0,0.0
4,Andhra Pradesh,Chittoor,1,14.144900,0.857263,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.615237,0.925098,0.507623,0.424843,0.737394,0.0,0.0,0.0

In [7]:
print(df.columns)

Index(['state', 'district', 'month', '1st', '2nd', '3rd', '4th', '5th', '6th',
       '7th', '8th', '9th', '10th', '11th', '12th', '13th', '14th', '15th',
       '16th', '17th', '18th', '19th', '20th', '21st', '22nd', '23rd', '24th',
       '25th', '26th', '27th', '28th', '29th', '30th', '31st'],
      dtype='object')

In [8]:
df.drop(['district', 'month'], axis=1, inplace=True)

df.head()

,state,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,...,22nd,23rd,24th,25th,26th,27th,28th,29th,30th,31st
0,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,Andhra Pradesh,0.379965,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.205834,0.671002,0.028994,0.0,0.0,0.0
4,Andhra Pradesh,14.144900,0.857263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.615237,0.925098,0.507623,0.424843,0.737394,0.0,0.0,0.0

In [9]:
daily_cols = df.columns[1:]  # skip 'state'

df[daily_cols] = df[daily_cols].apply(pd.to_numeric, errors='coerce')

In [10]:
df['Rainfall'] = df[daily_cols].sum(axis=1)

df.head()

,state,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,...,23rd,24th,25th,26th,27th,28th,29th,30th,31st,Rainfall
0,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000
1,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000
2,Andaman & Nicobar,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000
3,Andhra Pradesh,0.379965,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.205834,0.671002,0.028994,0.0,0.0,0.0,2.609365
4,Andhra Pradesh,14.144900,0.857263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.615237,0.925098,0.507623,0.424843,0.737394,0.0,0.0,0.0,26.160305

In [11]:
df = df.groupby('state')['Rainfall'].mean().reset_index()

In [12]:
df.rename(columns={'state': 'State'}, inplace=True)

df.head()

               State    Rainfall
0  Andaman & Nicobar    0.000000
1     Andhra Pradesh   80.778387
2  Arunachal Pradesh  219.886151
3              Assam  201.048883
4              Bihar   82.782091

In [13]:
df['Year'] = 2019

In [14]:
df['State'] = df['State'].str.upper()
df['State'] = df['State'].str.strip()

In [15]:
df.isnull().sum()

State       0
Rainfall    0
Year        0
dtype: int64

In [16]:
df.shape
df.head()

               State    Rainfall  Year
0  ANDAMAN & NICOBAR    0.000000  2019
1     ANDHRA PRADESH   80.778387  2019
2  ARUNACHAL PRADESH  219.886151  2019
3              ASSAM  201.048883  2019
4              BIHAR   82.782091  2019

In [19]:
df.to_csv(r"C:\AIML waterbourne project\New folder\environment_data.csv", index=False)