In [3]:
import pandas as pd

df = pd.read_csv(
    r"C:\\AIML waterbourne project\\datasets\\cleaned_datasets\\final_complete_dataset.csv"
)

df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year,Toilet_Access,Open_Defecation,Rainfall
0,LAKE,ANDHRA PRADESH,27,5.1,7.1,3270,1,0.65,2,800,2017,49.6,50.4,80.778387
1,LAKE,ANDHRA PRADESH,24,5.9,6.9,597,1.3,1.16,11,350,2017,49.6,50.4,80.778387
2,LAKE,ASSAM,20,2.2,5.7,50,1,0.1,300,360,2017,65.0,35.1,201.048883
3,LAKE,ASSAM,22,5.1,6.6,54,0.9,0.1,300,300,2017,65.0,35.1,201.048883
4,POND,ASSAM,22,0.7,6.8,263,4.5,0.8,1100,730,2017,65.0,35.1,201.048883

In [4]:
print(df.columns)

Index(['Type Water Body', 'State Name', 'Min Temperature',
       'Min Dissolved Oxygen', 'Min pH', 'Min Conductivity', 'Min BOD',
       'Min_Nitrate_Nitrite', 'Min Fecal Coliform', 'Min Total Coliform',
       'Year', 'Toilet_Access', 'Open_Defecation', 'Rainfall'],
      dtype='object')

In [5]:
def assign_risk(row):

    score = 0

    # Fecal coliform risk
    if row['Min Fecal Coliform'] > 500:
        score += 2
    elif row['Min Fecal Coliform'] > 100:
        score += 1

    # BOD risk
    if row['Min BOD'] > 3:
        score += 2
    elif row['Min BOD'] > 2:
        score += 1

    # Open defecation risk
    if row['Open_Defecation'] > 40:
        score += 2
    elif row['Open_Defecation'] > 20:
        score += 1

    # Toilet access risk
    if row['Toilet_Access'] < 50:
        score += 2
    elif row['Toilet_Access'] < 70:
        score += 1

    # Rainfall risk
    if row['Rainfall'] > 200:
        score += 2
    elif row['Rainfall'] > 100:
        score += 1

    # Temperature risk
    if row['Min Temperature'] > 35:
        score += 2
    elif row['Min Temperature'] > 30:
        score += 1

    # Dissolved Oxygen risk
    if row['Min Dissolved Oxygen'] < 3:
        score += 2
    elif row['Min Dissolved Oxygen'] < 5:
        score += 1

    # pH risk
    if row['Min pH'] < 6 or row['Min pH'] > 8.5:
        score += 2
    elif row['Min pH'] < 6.5 or row['Min pH'] > 8:
        score += 1

    # Final risk level
    if score >= 7:
        return "HIGH"

    elif score >= 4:
        return "MEDIUM"

    else:
        return "LOW"

In [6]:
numeric_columns = [
    'Min Fecal Coliform',
    'Min BOD',
    'Open_Defecation',
    'Toilet_Access',
    'Rainfall'
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [7]:
df.dtypes

Type Water Body          object
State Name               object
Min Temperature          object
Min Dissolved Oxygen     object
Min pH                   object
Min Conductivity         object
Min BOD                 float64
Min_Nitrate_Nitrite      object
Min Fecal Coliform      float64
Min Total Coliform       object
Year                      int64
Toilet_Access           float64
Open_Defecation         float64
Rainfall                float64
dtype: object

In [12]:
numeric_cols = [
    'Min Temperature',
    'Min Dissolved Oxygen',
    'Min pH',
    'Min BOD',
    'Min Fecal Coliform',
    'Toilet_Access',
    'Open_Defecation',
    'Rainfall'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Risk_Level'] = df.apply(assign_risk, axis=1)

df.head()

,Type Water Body,State Name,Min Temperature,Min Dissolved Oxygen,Min pH,Min Conductivity,Min BOD,Min_Nitrate_Nitrite,Min Fecal Coliform,Min Total Coliform,Year,Toilet_Access,Open_Defecation,Rainfall,Risk_Level
0,LAKE,ANDHRA PRADESH,27.0,5.1,7.1,3270,1.0,0.65,2.0,800,2017,49.6,50.4,80.778387,MEDIUM
1,LAKE,ANDHRA PRADESH,24.0,5.9,6.9,597,1.3,1.16,11.0,350,2017,49.6,50.4,80.778387,MEDIUM
2,LAKE,ASSAM,20.0,2.2,5.7,50,1.0,0.1,300.0,360,2017,65.0,35.1,201.048883,HIGH
3,LAKE,ASSAM,22.0,5.1,6.6,54,0.9,0.1,300.0,300,2017,65.0,35.1,201.048883,MEDIUM
4,POND,ASSAM,22.0,0.7,6.8,263,4.5,0.8,1100.0,730,2017,65.0,35.1,201.048883,HIGH

In [10]:
print(df[numeric_cols].dtypes)

Min Temperature         float64
Min Dissolved Oxygen    float64
Min pH                  float64
Min BOD                 float64
Min Fecal Coliform      float64
Toilet_Access           float64
Open_Defecation         float64
Rainfall                float64
dtype: object

In [11]:
df['Risk_Level'].value_counts()

Risk_Level
MEDIUM    1770
LOW       1335
HIGH       683
Name: count, dtype: int64

In [13]:
df.to_csv(
    r"C:\AIML waterbourne project\final_waterborne_risk_dataset.csv",
    index=False
)